version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name kadai-4-app --s3-location s3://cicd-artifact-bucket-4/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src